name: envied

packages:
  - "**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  test: >
    melos exec -c 1 "dart test --coverage=coverage"
  lcov: >
    melos exec -c 1 "dart pub global run coverage:test_with_coverage"
  coverage: >
    melos exec -c 1 "dart pub global run code_coverage -u"
  validate: >
    melos exec -c 1 "dart analyze && dart format . --set-exit-if-changed"
  format: >
    melos exec -c 1 "dart format ."
  doc: >
    melos exec -c 1 --ignore="example/**" "dart doc ."
  readme: >
    dart run scripts/propagate_readme.dart 
