name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 'stable'
      - name: Activate melos
        run: dart pub global activate melos
      - name: Bootstrap melos
        run: melos bs
      - name: Validate code
        run: melos run validate
      - name: Test code
        run: melos run test
      - name: Activate coverage
        run: dart pub global activate coverage
      - name: Run coverage
        run: melos run lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: packages/*/coverage/lcov.info